# 1.setup go env
# 2.build binary
# 3.upload to oss

name: build

on:
  push:
    branches:
      - 'main'
      - 'release*'

# This ensures that previous jobs for the branch are canceled when the branch is updated.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and upload
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.2'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags

      - name: Get branch name
        id: extract_branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: Build
        run:
          make build-release

      - name: Compress and Upload to OSS
        run: |
          pushd dist
          mkdir archives
          mv release_darwin_amd64_v1/blade archives/blade_darwin_amd64
          mv release_darwin_arm64/blade archives/blade_darwin_arm64
          mv release_linux_amd64_v1/blade archives/blade_linux_amd64
          mv release_linux_arm64/blade archives/blade_linux_arm64
          curl -sfL -O https://devtools.qiniu.com/qshell-v2.9.2-linux-amd64.tar.gz
          tar -xvf qshell-v2.9.2-linux-amd64.tar.gz
          chmod +x qshell
          ./qshell account ${{ secrets.QINIU_ACCESS_KEY }} ${{ secrets.QINIU_SECRET_KEY }} blade-uploader
          ./qshell qupload2 --overwrite --bucket ${{ secrets.QINIU_BUCKET }} --src-dir archives --key-prefix blade/${{ steps.extract_branch.outputs.branch }}/
          popd
