# 1.setup go env
# 2.build binary
# 3.upload to oss

name: build

on:
  push:
    branches:
      - 'main'
      - 'release*'

# This ensures that previous jobs for the branch are canceled when the branch is updated.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and upload
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.2'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags

      - name: Get branch name
        id: extract_branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: Build
        run:
          make build-release

      - name: Compress
        run: |
          pushd dist
          mkdir archives
          mv release_darwin_amd64_v1/blade archives/blade_darwin_amd64
          mv release_darwin_arm64/blade archives/blade_darwin_arm64
          mv release_linux_amd64_v1/blade archives/blade_linux_amd64
          mv release_linux_arm64/blade archives/blade_linux_arm64
          popd

      - name: Upload to OSS
        uses: hujiulong/action-qiniu-upload@master
        with:
          # Your qiniu access key, required.
          access_key: ${{ secrets.QINIU_ACCESS_KEY }}

          # Your qiniu secret key, required.
          secret_key: ${{ secrets.QINIU_SECRET_KEY }}

          # Bucket name, required.
          bucket: ${{ secrets.QINIU_BUCKET }}

          # The local directory (or file) you want to upload to bucket.
          # Default: './'
          source_dir: './dist/archives'

          # The directory inside of the bucket you want to upload to, namely key prefix prepended to dest file key.
          # Default: '/'
          dest_dir: /blade/${{ steps.extract_branch.outputs.branch }}

          # Whether to ignore source maps.
          # Default: true
          ignore_source_map: true
